SELECT INSTITUICAO.nome, CURSO.nome FROM INSTITUICAO AS I INNER JOIN INSTITUICAO_has_CURSO AS IC ON
	I.idINSTITUICAO = IC.INSTITUICAO_idINSTUICAO INNER JOIN CURSO AS C ON C.idCURSO = IC.CURSO_idCURSO
	WHERE C.total_cred < 200;
SELECT PROFESSORES.nome, DEPARTAMENTO.nome, PROJETOS.nome FROM PROFESSORES AS P INNER JOIN DEPARTAMENTO AS D ON
	D.idDEPARTAMENTO = P.DEPARTAMENTO_idDEPARTAMENTO INNER JOIN PROJETOS AS Q ON Q.DEPARTAMENTO_idDEPARTAMENTO = D.idDEPARTAMENTO
	WHERE Q.data_inicio > DATE('31/12/2018');
SELECT CURSO.nome FROM CURSO AS C INNER JOIN CURSO_has_DISCIPLINA AS CD ON
	C.idCURSO = CD.CURSO_idCURSO INNER JOIN DISCIPLINA AS D ON D.idDISCIPLINA = CD.DISCIPLINA_idDISCIPLINA
	WHERE D.nome = 'Cálculo 1';
SELECT DISCIPLINA.nome FROM DISCIPLINA AS D INNER JOIN CURSO_has_DISCIPLINA AS CD ON
	D.idDISCIPLINA = CD.DISCIPLINA_idDISCIPLINA INNER JOIN CURSO AS C ON 
	WHERE D.creditos = '6';
SELECT INSTITUICAO.nome, METODO_INGRESSO.num_vagas FROM INSITUICAO AS I INNER JOIN INSTITUICAO_has_METODO_INGRESSO AS IMI ON
	I.idINSTITUICAO = IMI.INSTITUICAO_idINSTUICAO INNER JOIN METODO_INGRESSO AS MI ON 
	MI.idMETODO_INGRESSO = IMI.METODO_INGRESSO_idMETODO_INGRESSO
	WHERE MI.nome = 'Negros' ORDER BY MI.num_vagas;