SELECT I.nome, C.nome FROM esdb.INSTITUICAO AS I INNER JOIN esdb.INSTITUICAO_has_CURSO AS IC ON
	I.idINSTITUICAO = IC.INSTITUICAO_idINSTItuiCAO INNER JOIN esdb.CURSO AS C ON C.idCURSO = IC.CURSO_idCURSO
	WHERE C.total_cred < 200;
SELECT P.nome, D.nome, q.nome FROM esdb.PROFESSORES AS P INNER JOIN esdb.DEPARTAMENTO AS D ON
	D.idDEPARTAMENTO = P.DEPARTAMENTO_idDEPARTAMENTO INNER JOIN esdb.PROJETOS AS Q ON Q.DEPARTAMENTO_idDEPARTAMENTO = D.idDEPARTAMENTO
	WHERE Q.data_inicio > '31/12/2018';
SELECT C.nome FROM esdb.CURSO AS C INNER JOIN esdb.CURSO_has_DISCIPLINA AS CD ON
	C.idCURSO = CD.CURSO_idCURSO INNER JOIN esdb.DISCIPLINA AS D ON D.idDISCIPLINA = CD.DISCIPLINA_idDISCIPLINA
	WHERE D.nome = 'Cálculo 1';
SELECT D.nome FROM esdb.DISCIPLINA AS D INNER JOIN esdb.CURSO_has_DISCIPLINA AS CD ON 
	D.idDISCIPLINA = CD.DISCIPLINA_idDISCIPLINA INNER JOIN esdb.CURSO AS C ON c.idcurso = cd.curso_idcurso 
	WHERE D.creditos = '6';
SELECT I.nome, MI.num_vagas FROM esdb.INStiTUICAO AS I INNER JOIN esdb.INSTITUICAO_has_METODO_INGRESSO AS IMI ON
	I.idINSTITUICAO = IMI.INSTITUICAO_idINStiTUICAO INNER JOIN esdb.METODO_INGRESSO AS MI ON 
	MI.idMETODO_INGRESSO = IMI.METODO_INGRESSO_idMETODO_INGRESSO
WHERE MI.nome = 'Negros' ORDER BY MI.num_vagas;
select * from instituicao;
insert into INSTITUICAO values(39013,'UnB','DF','Darcy Ribeiro',1961,load_file('C:\Users\Gabriel\Desktop\unb.png')); 
